DROP SCHEMA IF EXISTS TaupeMeubles;
CREATE DATABASE IF NOT EXISTS TaupeMeubles;
USE TaupeMeubles;

-- Table des utilisateurs
CREATE TABLE IF NOT EXISTS USERS
(
    LOGIN     VARCHAR(100) PRIMARY KEY,
    PASS      VARCHAR(100) NOT NULL,
    EMAIL     VARCHAR(255) NOT NULL UNIQUE,
    NOM       VARCHAR(50),
    PRENOM    VARCHAR(50),
    DATE      VARCHAR(50),
    SEXE      VARCHAR(10),
    ADRESSE   VARCHAR(500),
    CODEP     VARCHAR(50),
    VILLE     VARCHAR(50),
    TELEPHONE VARCHAR(15)
);


-- Table des produits
CREATE TABLE IF NOT EXISTS PRODUITS
(
    ID_PROD INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE VARCHAR(100) NOT NULL,
    PRIX    FLOAT NOT NULL,
    DESCRIPTIF VARCHAR(500),
    PHOTO  VARCHAR(255) #TODO Modifier?
);

-- Table des rubriques (catégories de meubles)
CREATE TABLE IF NOT EXISTS RUBRIQUES
(
    ID_RUB INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_RUB VARCHAR(100) NOT NULL
);

-- Table des commandes
CREATE TABLE IF NOT EXISTS COMMANDES
(
    ID_COM INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT  VARCHAR(100), #TODO Vérifier
    ID_PROD    INT,
    DATE       VARCHAR(50),
    ADRESSE   VARCHAR(500),
    CP        VARCHAR(50),
    VILLE      VARCHAR(50),
    FOREIGN KEY (ID_CLIENT) REFERENCES USERS(LOGIN), #TODO Vérifier si c'est vrmnt ca
    FOREIGN KEY (ID_PROD) REFERENCES PRODUITS(ID_PROD)
);

-- Table des hierarchies entre rubriques et produits
CREATE TABLE IF NOT EXISTS HIERARCHIES
(
    ID_PARENT INT,
    ID_ENFANT INT
);

-- Table des favoris
CREATE TABLE IF NOT EXISTS FAVS
(
    LOGIN VARCHAR(100),
    ID_PROD INT,
    PRIMARY KEY (LOGIN, ID_PROD),
    FOREIGN KEY (LOGIN) REFERENCES USERS(LOGIN),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUITS(ID_PROD)
);


