DROP SCHEMA IF EXISTS TaupeMeubles;
CREATE DATABASE IF NOT EXISTS TaupeMeubles;
USE TaupeMeubles;

-- Table des utilisateurs
CREATE TABLE IF NOT EXISTS USERS
(
    ID_USER   INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN     VARCHAR(100) NOT NULL UNIQUE,
    PASS      VARCHAR(100) NOT NULL,
    EMAIL     VARCHAR(255) NOT NULL UNIQUE,
    NOM       VARCHAR(50),
    PRENOM    VARCHAR(50),
    DATE      VARCHAR(50),
    SEXE      VARCHAR(10),
    ADRESSE   VARCHAR(500),
    CODEP     VARCHAR(50),
    VILLE     VARCHAR(50),
    TELEPHONE VARCHAR(15)
);


-- Table des produits
CREATE TABLE IF NOT EXISTS PRODUITS
(
    ID_PROD INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE VARCHAR(100) NOT NULL,
    PRIX    FLOAT NOT NULL,
    DESCRIPTIF VARCHAR(500),
    PHOTO  VARCHAR(255) #TODO Modifier?
);

-- Table des rubriques (catégories de meubles)
CREATE TABLE IF NOT EXISTS RUBRIQUES
(
    ID_RUB INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_RUB VARCHAR(100) NOT NULL
);

-- Table des commandes
CREATE TABLE IF NOT EXISTS COMMANDES
(
    ID_COM INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT  INT,
    ID_PROD    INT,
    DATE       VARCHAR(50),
    ADRESSE   VARCHAR(500),
    CP        VARCHAR(50),
    VILLE      VARCHAR(50)
);

-- Table des hierarchies entre rubriques et produits
CREATE TABLE IF NOT EXISTS HIERARCHIES
(
    ID_PARENT INT,
    ID_ENFANT INT
);


